"""create message table

Revision ID: 0570797d00e4
Revises: 
Create Date: 2025-05-30 22:18:09.799055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0570797d00e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('link_id', sa.String(length=50), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_active', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_active')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('link_id')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
